from os import system as cmd
from progress.bar import IncrementalBar
import os
import random
import time
import hashlib

cmd('mode con: cols=80 lines=20')
cmd('title HACKERS OS')
if cmd('cd data') != 0:
	cmd('mkdir data')
cmd('cls')

def logo():
	if os.path.exists('data\\key.txt'):
		while True:
			file = open('data\\key.txt', 'r')
			passwd = file.read()
			file.close()
			cmd('cls')
			print('')
			print('              HACKER OS 1.4v')
			print('              Enter password')
			pas = input('              >')
			hashs = hashlib.md5(pas.encode())
			if hashs.hexdigest() == passwd:
				print('              Success!')
				break
	else:
		print('')
		print('              HACKER OS 1.4v')
		print('         come up with a password')
		pas = input('              >')
		hashs = hashlib.md5(pas.encode())
		file = open('data\\key.txt', 'w')
		file.write(hashs.hexdigest())
		file.close()

def select():
	cmd('cls')
	print('Select to hack:')
	print('1. Gmail\n2. Vk\n3. Telegram\n4. What`s App\n5. Discord\n6. Minecraft\n7. Steam')
def goto(sel):
	if int(sel) == 1:
		Gmail()
	if int(sel) == 2:
		Vk()
	if int(sel) == 3:
		Tl()
	if int(sel) == 4:
		Wa()
	if int(sel) == 5:
		DI()
	if int(sel) == 6:
		MC()
	if int(sel) == 7:
		St()
def Gmail():
	cmd('cls')
	mail = input('Enter gmail: ')
	time.sleep(0.5)
	print('Gmail to hack --> ' + mail + '@gmail.com')
	time.sleep(0.3)
	print('[+] Connecting to --> gmail.com')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking servers', max=100, suffix='%(percent)d%%')
	for i in range(100):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Servers has hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Find looking for data about gmail', max=50, suffix='%(percent)d%%')
	for i in range(50):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Data detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Decrypting the password', max=200, suffix='%(percent)d%%')
	for i in range(200):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Password decrypted')
	time.sleep(0.5)
	print('')
	c = '[HACKED]    ' + mail + '@gmail.com' + passgen('abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', 8, 12)
	print(c)
	print('')
	cmd('echo ' + c + ' >> data\\log.txt')
	input('To return, press enter')
def Vk():
	cmd('cls')
	nu = input('Enter telephon number: ')
	time.sleep(0.5)
	chose = '+7 (' + nu[1:4] + ') ' + nu[4:7] + '-' + nu[7:9] + '-' + nu[9:11]
	print('Number to hack --> ' + chose)
	time.sleep(0.3)
	print('[+] Connecting to --> vk.com')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking servers', max=120, suffix='%(percent)d%%')
	for i in range(120):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Servers has hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Search code of vk', max=80, suffix='%(percent)d%%')
	for i in range(80):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Decrypting the code', max=40, suffix='%(percent)d%%')
	for i in range(40):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code decrypted')
	time.sleep(0.5)
	print('')
	c = '[HACKED]    ' + nu + passgen('0123456789', 4, 4)
	print(c)
	print('')
	cmd('echo ' + c + ' >> data\\log.txt')
	input('To return, press enter')
def Tl():
	cmd('cls')
	nu = input('Enter telephon number: ')
	time.sleep(0.5)
	chose = '+7 (' + nu[1:4] + ') ' + nu[4:7] + '-' + nu[7:9] + '-' + nu[9:11]
	print('Number to hack --> ' + chose)
	time.sleep(0.3)
	print('[+] Connecting to --> telegram')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking servers', max=250, suffix='%(percent)d%%')
	for i in range(250):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Servers has hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Find code of telegram', max=80, suffix='%(percent)d%%')
	for i in range(80):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Decrypting the code', max=80, suffix='%(percent)d%%')
	for i in range(80):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code decrypted')
	time.sleep(0.5)
	print('')
	c = '[HACKED]    ' + nu + passgen('0123456789', 5, 5)
	print(c)
	print('')
	cmd('echo ' + c + ' >> data\\log.txt')
	input('To return, press enter')
def Wa():
	cmd('cls')
	nu = input('Enter telephon number: ')
	time.sleep(0.5)
	chose = '+7 (' + nu[1:4] + ') ' + nu[4:7] + '-' + nu[7:9] + '-' + nu[9:11]
	print('Number to hack --> ' + chose)
	time.sleep(0.3)
	print('[+] Connecting to --> What`s App')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking servers', max=20, suffix='%(percent)d%%')
	for i in range(20):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Servers has hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Search code of WA', max=50, suffix='%(percent)d%%')
	for i in range(50):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Decrypting the code', max=50, suffix='%(percent)d%%')
	for i in range(50):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code decrypted')
	time.sleep(0.5)
	print('')
	c = '[HACKED]    ' + nu + passgen('0123456789', 6, 6)
	print(c)
	print('')
	cmd('echo ' + c + ' >> data\\log.txt')
	input('To return, press enter')
def DI():
	cmd('cls')
	gmail = input('Enter gmail: ')
	time.sleep(0.5)
	print('Gmail to hack --> ' + gmail + '@gmail.com')
	time.sleep(0.3)
	print('[+] Connecting to --> gmail.com')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking servers', max=100, suffix='%(percent)d%%')
	for i in range(100):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Servers has hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Search code of DS', max=20, suffix='%(percent)d%%')
	for i in range(20):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Decrypting the code', max=40, suffix='%(percent)d%%')
	for i in range(40):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code decrypted')
	time.sleep(0.5)
	print('')
	c = '[HACKED]    ' + gmail + '@gmail.com' + passgen('0123456789', 6, 6)
	print(c)
	print('')
	cmd('echo ' + c + ' >> data\\log.txt')
	input('To return, press enter')
def MC():
	cmd('cls')
	nick = input('Enter minecraft nick: ')
	time.sleep(0.5)
	print('Nick to hack --> ' + nick)
	time.sleep(0.3)
	print('[+] Connecting to --> minecraft.net')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking servers', max=150, suffix='%(percent)d%%')
	for i in range(150):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Servers has hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Search gmail of nick', max=40, suffix='%(percent)d%%')
	for i in range(40):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Gmail detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking gmail', max=100, suffix='%(percent)d%%')
	for i in range(100):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Gmail hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Search code on gmail', max=20, suffix='%(percent)d%%')
	for i in range(20):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Decrypting the code', max=40, suffix='%(percent)d%%')
	for i in range(40):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Code decrypted')
	time.sleep(0.5)
	print('')
	c = '[HACKED]    ' + nick + passgen('abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', 8, 12)
	print(c)
	print('')
	cmd('echo ' + c + ' >> data\\log.txt')
	input('To return, press enter')
def St():
	cmd('cls')
	nick = input('Enter steam nick: ')
	time.sleep(0.5)
	print('Nick to hack --> ' + nick)
	time.sleep(0.3)
	print('[+] Connecting to --> steam.com')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking servers', max=150, suffix='%(percent)d%%')
	for i in range(150):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Servers has hacked')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Search  Steam name of nick', max=40, suffix='%(percent)d%%')
	for i in range(40):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Name detected')
	time.sleep(0.5)
	bar = IncrementalBar('[*] Hacking password', max=100, suffix='%(percent)d%%')
	for i in range(100):
		bar.next()
		time.sleep(0.1)
	bar.finish()
	time.sleep(0.5)
	print('[+] Password hacked')
	time.sleep(0.5)
	print('')
	c = '[HACKED]    __' + nick + '__' + passgen('abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', 8, 12)
	print(c)
	print('')
	cmd('echo ' + c + ' >> data\\log.txt')
	input('To return, press enter')
def passgen(chars, min, max):
	length = random.randint(min, max)
	password = ":"
	for i in range(length):
		password += random.choice(chars)
	return password
if __name__ == '__main__':
	logo()
	while True:
		select()
		sel = input('>')
		goto(sel)